# Generated by Django 3.2.9 on 2021-12-03 11:02

from django.db import migrations, models
import isbn_field.fields
import isbn_field.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('isbn', isbn_field.fields.ISBNField(clean_isbn=False, max_length=28, validators=[isbn_field.validators.ISBNValidator], verbose_name='ISBN')),
                ('author', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('number_of_pages', models.IntegerField()),
                ('publisher', models.CharField(max_length=100)),
                ('release_date', models.DateField(max_length=100)),
            ],
        ),
    ]
